
// This file has been generated by the GUI designer. Do not modify.
namespace SlidingPuzzle.Views
{
    public partial class GameWindow
    {
        private global::Gtk.UIManager UIManager;
		
        private global::Gtk.Action GameAction;
		
        private global::Gtk.Action NewGameAction;
		
        private global::Gtk.Action RetryAction;
		
        private global::Gtk.Action GameSize3Action;
		
        private global::Gtk.Action GameSize4Action;
		
        private global::Gtk.Action GameSize5Action;
		
        private global::Gtk.VBox vbox1;
		
        private global::Gtk.MenuBar GameMenuBar;
		
        private global::Gtk.DrawingArea GameDrawArea;

        protected virtual void Build()
        {
            global::Stetic.Gui.Initialize(this);
            // Widget SlidingPuzzle.Views.GameWindow
            this.UIManager = new global::Gtk.UIManager();
            global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
            this.GameAction = new global::Gtk.Action("GameAction", global::Mono.Unix.Catalog.GetString("Game"), null, null);
            this.GameAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Game");
            w1.Add(this.GameAction, null);
            this.NewGameAction = new global::Gtk.Action("NewGameAction", global::Mono.Unix.Catalog.GetString("New"), null, null);
            this.NewGameAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New");
            w1.Add(this.NewGameAction, null);
            this.RetryAction = new global::Gtk.Action("RetryAction", global::Mono.Unix.Catalog.GetString("Retry"), null, null);
            this.RetryAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Retry");
            w1.Add(this.RetryAction, null);
            this.GameSize3Action = new global::Gtk.Action("GameSize3Action", global::Mono.Unix.Catalog.GetString("3x3"), null, null);
            this.GameSize3Action.ShortLabel = global::Mono.Unix.Catalog.GetString("3x3");
            w1.Add(this.GameSize3Action, null);
            this.GameSize4Action = new global::Gtk.Action("GameSize4Action", global::Mono.Unix.Catalog.GetString("4x4"), null, null);
            this.GameSize4Action.ShortLabel = global::Mono.Unix.Catalog.GetString("4x4");
            w1.Add(this.GameSize4Action, null);
            this.GameSize5Action = new global::Gtk.Action("GameSize5Action", global::Mono.Unix.Catalog.GetString("5x5"), null, null);
            this.GameSize5Action.ShortLabel = global::Mono.Unix.Catalog.GetString("5x5");
            w1.Add(this.GameSize5Action, null);
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "SlidingPuzzle.Views.GameWindow";
            this.Title = global::Mono.Unix.Catalog.GetString("Slider Puzzle");
            this.WindowPosition = ((global::Gtk.WindowPosition)(1));
            this.Resizable = false;
            this.AllowGrow = false;
            // Container child SlidingPuzzle.Views.GameWindow.Gtk.Container+ContainerChild
            this.vbox1 = new global::Gtk.VBox();
            this.vbox1.Name = "vbox1";
            // Container child vbox1.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><menubar name='GameMenuBar'><menu name='GameAction' action='GameAction'><menu name='NewGameAction' action='NewGameAction'><menuitem name='GameSize3Action' action='GameSize3Action'/><menuitem name='GameSize4Action' action='GameSize4Action'/><menuitem name='GameSize5Action' action='GameSize5Action'/></menu><menuitem name='RetryAction' action='RetryAction'/></menu></menubar></ui>");
            this.GameMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/GameMenuBar")));
            this.GameMenuBar.Name = "GameMenuBar";
            this.vbox1.Add(this.GameMenuBar);
            global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GameMenuBar]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.GameDrawArea = new global::Gtk.DrawingArea();
            this.GameDrawArea.WidthRequest = 480;
            this.GameDrawArea.HeightRequest = 480;
            this.GameDrawArea.Name = "GameDrawArea";
            this.vbox1.Add(this.GameDrawArea);
            global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GameDrawArea]));
            w3.Position = 1;
            this.Add(this.vbox1);
            if ((this.Child != null))
            {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 480;
            this.DefaultHeight = 530;
            this.Show();
            this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnKeyPressEvent);
            this.RetryAction.Activated += new global::System.EventHandler(this.OnRetryActionActivated);
            this.GameSize3Action.Activated += new global::System.EventHandler(this.OnGameSize3ActionActivated);
            this.GameSize4Action.Activated += new global::System.EventHandler(this.OnGameSize4ActionActivated);
            this.GameSize5Action.Activated += new global::System.EventHandler(this.OnGameSize5ActionActivated);
        }
    }
}
